import { supabase } from '../services/supabaseClient';
import type { Excuse } from '../types/domain.types';
import { isValidUUID } from '../utils/uuid';

export interface SaveExcusePayload {
  user_id?: string;
  input_context: string;
  generated_text: string;
  tone_id?: string;
  model_id?: string;
  used_temperature: number;
  used_max_tokens: number;
  status: string;
  favorite?: boolean;
  generation_time_ms?: number;
  prompt_template_id?: string;
  ai_settings_id?: string;
  error_message?: string;
}

export const excusesRepository = {
  /**
   * Persists a generated excuse record in the database.
   * Sanitizes UUID fields to prevent 22P02 Postgres errors.
   */
  async save(excuse: SaveExcusePayload): Promise<Excuse> {
    const payload = {
      ...excuse,
      user_id: isValidUUID(excuse.user_id) ? excuse.user_id : undefined,
      tone_id: isValidUUID(excuse.tone_id) ? excuse.tone_id : undefined,
      model_id: isValidUUID(excuse.model_id) ? excuse.model_id : undefined,
      prompt_template_id: isValidUUID(excuse.prompt_template_id) ? excuse.prompt_template_id : undefined,
      ai_settings_id: isValidUUID(excuse.ai_settings_id) ? excuse.ai_settings_id : undefined,
      updated_at: new Date().toISOString()
    };

    const { data, error } = await (supabase.from('excuses' as any) as any)
      .insert(payload)
      .select()
      .single();

    if (error) throw error;
    return data as Excuse;
  },

  /**
   * Retrieves all excuses generated by a specific user.
   */
  async getByUser(userId: string): Promise<Excuse[]> {
    if (!isValidUUID(userId)) {
      return [];
    }

    const { data, error } = await (supabase.from('excuses' as any) as any)
      .select('*')
      .eq('user_id', userId)
      .is('deleted_at', null)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return (data as Excuse[]) || [];
  },

  /**
   * Toggles the favorite status of a specific excuse record.
   */
  async setFavorite(id: string, favorite: boolean): Promise<Excuse> {
    if (!isValidUUID(id)) {
      throw new Error(`ID de desculpa inválido: ${id}`);
    }

    const payload = {
      favorite,
      updated_at: new Date().toISOString()
    };

    const { data, error } = await (supabase.from('excuses' as any) as any)
      .update(payload)
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;
    return data as Excuse;
  },

  /**
   * Soft deletes an excuse record.
   */
  async delete(id: string): Promise<Excuse> {
    if (!isValidUUID(id)) {
      throw new Error(`ID de desculpa inválido: ${id}`);
    }

    const payload = {
      deleted_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    };

    const { data, error } = await (supabase.from('excuses' as any) as any)
      .update(payload)
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;
    return data as Excuse;
  }
};
