import { supabase } from '../services/supabaseClient';

export interface SaveExcusePayload {
  user_id?: string;
  input_context: string;
  generated_text: string;
  tone_id?: string;
  model_id?: string;
  used_temperature: number;
  used_max_tokens: number;
  status: string;
  favorite?: boolean;
  generation_time_ms?: number;
  prompt_template_id?: string;
  ai_settings_id?: string;
  error_message?: string;
}

export const excusesRepository = {
  /**
   * Persists a generated excuse record in the database.
   */
  async save(excuse: SaveExcusePayload) {
    const payload = {
      ...excuse,
      updated_at: new Date().toISOString()
    };

    const { data, error } = await (supabase.from('excuses' as any) as any)
      .insert(payload)
      .select()
      .single();

    if (error) throw error;
    return data;
  },

  /**
   * Retrieves all excuses generated by a specific user.
   */
  async getByUser(userId: string) {
    const { data, error } = await (supabase.from('excuses' as any) as any)
      .select('*')
      .eq('user_id', userId)
      .is('deleted_at', null)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return data || [];
  },

  /**
   * Toggles the favorite status of a specific excuse record.
   */
  async setFavorite(id: string, favorite: boolean) {
    const payload = {
      favorite,
      updated_at: new Date().toISOString()
    };

    const { data, error } = await (supabase.from('excuses' as any) as any)
      .update(payload)
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;
    return data;
  },

  /**
   * Performs soft deletion by setting deleted_at to current timestamp.
   */
  async softDelete(id: string) {
    const payload = {
      deleted_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    };

    const { data, error } = await (supabase.from('excuses' as any) as any)
      .update(payload)
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;
    return data;
  }
};
